version: '3'
services:
  db_data:
    image: busybox
    volumes:
      - type: bind
        source: "./db/conf.d/my.cnf"
        target: "/etc/mysql/conf.d/my.cnf"
  db:
    image: mysql:5.7
    volumes_from:
      - db_data
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ddd
      MYSQL_ROOT_PASSWORD: password
