version: '3'
services:
  db_data:
    image: busybox
    # command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    volumes:
      - /var/lib/mysql
  db:
    image: mysql:5.7
    volumes_from:
      - db_data
    ports:
      - '3306:3306'
    environment:
      MYSQL_DATABASE: ddd
      MYSQL_ROOT_PASSWORD: password
