@startuml ユースケース図
left to right direction
actor 作業者
rectangle タスク管理 {
    rectangle 今回のモデリングのスコープ {
        作業者 --> (タスクを登録する)
        作業者 --> (タスクを延期する)
        作業者 --> (タスクを完了する)
        作業者 --> (タスクの担当者を設定する)
    }
    作業者 --> (タスクからカレンダーを登録する)
}
@enduml